// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA07FkTQFFSKGDaQZMHa8KvuZggphUzPco',
    appId: '1:595088395482:web:48f8bd1d0ff7b8c1fda9e3',
    messagingSenderId: '595088395482',
    projectId: 'my-crud-app-a969c',
    authDomain: 'my-crud-app-a969c.firebaseapp.com',
    databaseURL: 'https://my-crud-app-a969c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-crud-app-a969c.appspot.com',
    measurementId: 'G-Q22W67F4DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPmrsADVrG7JE7-eAm1E6As76E0OkKU3M',
    appId: '1:595088395482:android:8ed8109409b8ff41fda9e3',
    messagingSenderId: '595088395482',
    projectId: 'my-crud-app-a969c',
    databaseURL: 'https://my-crud-app-a969c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-crud-app-a969c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUnWXNXH8EAwbO3cNCeoeaTelQeTNCI7k',
    appId: '1:595088395482:ios:a1e65789241f5aa4fda9e3',
    messagingSenderId: '595088395482',
    projectId: 'my-crud-app-a969c',
    databaseURL: 'https://my-crud-app-a969c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-crud-app-a969c.appspot.com',
    iosBundleId: 'com.example.myCrudApp',
  );
}
